# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mariadb:10.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 127.0.0.1:3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:8080:8080